### ISSUE TITLE
Cant mount correctly to downloads folder.

### ISSUE THREAD

**Issue by frederiktoft** [Bockiii/deezloadermx-docker#1]
Firstly, I apologize if I mess with the terminologies, but I'm quite new to docker. 
There is an issue with mounting a volume to the downloads folder. I can successfully mount a volume to the config folder (/config) as per your instruction, but the downloads folder (/downloads) does not work. If I however directly mount to /root/Deezloader Music/ then everything works as it should.

**Comment by Bockiii** [comment]
Hi, thanks for the info, I will look into this.

**Comment by Bockiii** [comment]
Hi, fixed it. The symlink was somehow missing in the dockerfile. It's there now and tested. Just recreate your docker with the latest image.
