### ISSUE TITLE
Permission error on folder log

### ISSUE THREAD

**Issue by Ansem93** [Bockiii/deezloadermx-docker#12]
Hi,
I'm trying to run this container but I get this error:

> /home/deezer/deezloaderremix/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:45
>         throw err0
>         ^
> 
> Error: EACCES: permission denied, mkdir '/home/deezer/.config/Deezloader Remix/logs'
>     at Object.mkdirSync (fs.js:823:3)
>     at Object.mkdirsSync (/home/deezer/deezloaderremix/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
>     at Object.<anonymous> (/home/deezer/deezloaderremix/app/utils/logger.js:7:4)
>     at Module._compile (internal/modules/cjs/loader.js:959:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/home/deezer/deezloaderremix/app/app.js:37:16)
>     at Module._compile (internal/modules/cjs/loader.js:959:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
>     at internal/main/run_main_module.js:17:11 {
>   errno: -13,
>   syscall: 'mkdir',
>   code: 'EACCES',
>   path: '/home/deezer/.config/Deezloader Remix/logs'
> }

I keep the folders of my containers all in the same folder, so it should have the same permission of all other folders. 
This is the past that I use for /config:
/Discks/Docker/Configuration/Deezloader_Remix
I tried to run the container even with root permission (pgid and puid 0), but I still get this error.

**Comment by Bockiii** [comment]
Hi,

Can you give me some more info:
- Which container tag are you using?
- Which host system are you using?
- What command do you use to start the container? Full command pls.

If you created the local folder with a user that you are not using for the container, you might need to chown the folder to the user id that you use in the container.

**Comment by Ansem93** [comment]
Which container tag are you using? -> latest
    Which host system are you using? -> Open Media Vault 4, it's a debian stable distro
    What command do you use to start the container? Full command pls.
Sorry, I manage my containers thought a webui, so I'm not sur about the exact command.
This are my settings:
![immagine](https://user-images.githubusercontent.com/6626218/72572149-e892cd80-38c1-11ea-8ab4-b118a1915ebf.png)
![immagine](https://user-images.githubusercontent.com/6626218/72572172-f9434380-38c1-11ea-909c-df819a36e9fc.png)

The weird thing is this:
![immagine](https://user-images.githubusercontent.com/6626218/72572219-20017a00-38c2-11ea-8eac-eb187b1c8fb2.png)
As you can see every container but watchtower have as command "/init" while deezerload have "node app.js"

**Comment by Ansem93** [comment]
Also, this is the detail file:
`[
    {
        "Id": "216f9e4d03811152bbffdb37902ce82691fcd906425c4dedc63d339ce40950a5",
        "Created": "2020-01-11T22:59:38.543667984Z",
        "Path": "node",
        "Args": [
            "app.js"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2020-01-16T23:19:17.368039689Z",
            "FinishedAt": "2020-01-16T23:19:17.75719054Z"
        },
        "Image": "sha256:39134df20ec43fa9a8a63fd792e0b3dc80b68d8518618a8bd15240339ca5534f",
        "ResolvConfPath": "/var/lib/docker/containers/216f9e4d03811152bbffdb37902ce82691fcd906425c4dedc63d339ce40950a5/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/216f9e4d03811152bbffdb37902ce82691fcd906425c4dedc63d339ce40950a5/hostname",
        "HostsPath": "/var/lib/docker/containers/216f9e4d03811152bbffdb37902ce82691fcd906425c4dedc63d339ce40950a5/hosts",
        "LogPath": "/var/lib/docker/containers/216f9e4d03811152bbffdb37902ce82691fcd906425c4dedc63d339ce40950a5/216f9e4d03811152bbffdb37902ce82691fcd906425c4dedc63d339ce40950a5-json.log",
        "Name": "/DeezerloaderRemix",
        "RestartCount": 8,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/localtime:/etc/localtime:ro",
                "/Dischi/6TB/Musica nuova/Deezerload:/downloads:rw",
                "/Dischi/Docker/Configurazione/Deezloader_Remix:/config:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/69b0c353c771b385ceade3a89d2f02afbc4fd7843874c5deeb366ee3ee245c97-init/diff:/var/lib/docker/overlay2/f633538598757f8572ab20e6785cc8f7cd850f1ba25b8c19b04b793f0bf114a0/diff:/var/lib/docker/overlay2/e4001a129d79cadbc43e7c9c4720e35d89bb39d8750c1a82ca692cafc03cfe95/diff:/var/lib/docker/overlay2/9e0e7b759135378ef09bd80f8fabd8443c8915ab43ae6f61592380ac8866bd32/diff:/var/lib/docker/overlay2/5cb2f307abfdf434b7f5123002aec28b6c5aa59e4533ca2218375ddaf0d7929d/diff:/var/lib/docker/overlay2/6ba3f2a0a002f7f5a8f7780127fb229f18f83af781d901f2d1d9cd68ce16722c/diff",
                "MergedDir": "/var/lib/docker/overlay2/69b0c353c771b385ceade3a89d2f02afbc4fd7843874c5deeb366ee3ee245c97/merged",
                "UpperDir": "/var/lib/docker/overlay2/69b0c353c771b385ceade3a89d2f02afbc4fd7843874c5deeb366ee3ee245c97/diff",
                "WorkDir": "/var/lib/docker/overlay2/69b0c353c771b385ceade3a89d2f02afbc4fd7843874c5deeb366ee3ee245c97/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/Dischi/6TB/Musica nuova/Deezerload",
                "Destination": "/downloads",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/Dischi/Docker/Configurazione/Deezloader_Remix",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "Delibird",
            "Domainname": "",
            "User": "deezer",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1730/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "NODEVERSION=v12.14.0",
                "PGID=100",
                "PUID=1002",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/deezer/node/bin"
            ],
            "Cmd": [
                "node",
                "app.js"
            ],
            "Image": "brosftw/deezerloader:latest",
            "Volumes": {
                "/config": {},
                "/downloads": {}
            },
            "WorkingDir": "/home/deezer/deezloaderremix/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "20190927",
                "org.label-schema.license": "GPLv2",
                "org.label-schema.name": "CentOS Base Image",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "CentOS"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "9378b0aac1fae671d75b58cd99d92e2b809be1c0cf4d4032eac1ff7069359d89",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "e91befbc5aa729fc9222850ca8662466a3e6b2a772dcfd1de16b7f6b48263fcf",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]`

**Comment by Bockiii** [comment]
Hi,

thats a completely different docker image :) Use the correct one and it should work. Name is in the description of the container.
