### ISSUE TITLE
Mount to a folder outside the Docker directory

### ISSUE THREAD

**Issue by geekaroni** [Bockiii/deezloadermx-docker#16]
I'm running this on my Synology and it works great. The only problem I have is it wants me to mount the downloads to a folder within the Synology docker directory. I'm using Audio Station and it indexes a folder called music in the root directory. Any way I can get the audio to download there without too much trouble?

**Comment by Bockiii** [comment]
If synology only lets you mount into a specific docker subfolder, you could make a symlink on your synology to map the audio station folder to the symlinked folder that links to your audio folder...

follow me? :)

**Comment by geekaroni** [comment]
I tried this and it will not index a symlinked folder unfortunately. Worth a try though!

**Comment by Bockiii** [comment]
Did you link the wrong way around? The actual folder should be the one in root, the sym folder should be the one mapped in docker. For the audio station, nothing should have changed

**Comment by geekaroni** [comment]
sudo mount --bind /volume1/docker/deez/Music /volume1/music

This is what I used.

**Comment by Bockiii** [comment]
my (non tested) solution would be:
Assumptions
Folder where you want to music to live: /volume1/music
Folder within docker structure where deezloader maps to: /volume1/docker/deez/Music

Then I would do this:
1) remove the deez/Music folder
2) use "sudo ln -s /volume1/music /volume1/docker/deez/Music" on the synology command line

I assume symlinking will work better than mounting, but like I said... untested. If it doesnt work, switch around the volume order on your mount --bind command. That might work as well.

**Comment by geekaroni** [comment]
I was able to fix this by running a perl script and scheduled task to index the folder automatically. The issue is Synology only indexes files via FTP, SMB or DFP so any files downloaded directly to the folder were not being indexed until I dug around the internet and found a script thanks to a good friend of mine. If anyone needs this script just poke me here.

**Comment by Bockiii** [comment]
Okay, so maybe someone who stumbles over this in the future can use it as well.

If you can, could you link the script? You can just dump it into a pastebin for example and link it. Thanks!

**Comment by sauvageb** [comment]
@geekaroni Can you give us your configuration for mount volumes, and your script about folder's autoindexing ? 

For my part, docker container bind configuration is below : 
/downloads music/deezer

And I have set up an schedule task every 30 minutes : 
`/usr/syno/bin/synoindex -R /volume1/music`

What do you think about this ? @Bockiii

**Comment by Bockiii** [comment]
I don't have a synology, so I have no opinion on your solution ;)

But it sounds reasonable.
