### ISSUE TITLE
Permissions of downloaded files

### ISSUE THREAD

**Issue by steve1977** [Bockiii/deezloadermx-docker#17]
Docker is up and running (on Unraid). Things seem to work and I can well download. However, downloaded files are ready-only (permission issue). I included PUID and PGID, but doesn't help. Even set it as "0", but also doesn't help. Any idea how to fix this?

**Comment by steve1977** [comment]
I noticed one thing. The "first" folder (artist) has "write" permission, while the second (album) does not and neither has the file. When disabling artist folder, album folder works, but track still not.

**Comment by Bockiii** [comment]
try puid guid "1000". That should be the unraid default user. If you have another user that is running the docker stuff, enter that PUID GUID.

**Comment by steve1977** [comment]
Mmh... Unfortunately not working. I realized one thing that could help trouble-shooting. If I disable the script to create artist and album folders, the file permissions are fine. What creates trouble is the creation of these folders.

And on separate note, the docker is no longer using the latest version. Any chance to update it?

Thanks!!!

**Comment by Bockiii** [comment]
I don't run unraid, so I have no chance of testing this. I just recreated this on my local docker host and it worked fine, including folder creation. This may be down to unraid and your user management. Apart from telling the container which user/group to use, I have no impact on the scripts that deezloader runs.

The container is still using the latest release (4.3.0), so I don't know what you mean.

Are you using the dev tag?

**Comment by Bockiii** [comment]
pinging @steve1977

**Comment by Bockiii** [comment]
I dont think this is an issue with the container and comes down to how you are using it. I can't replicate it.
