### ISSUE TITLE
Can't get it working on Raspberry Pi

### ISSUE THREAD

**Issue by titouan-pellerin** [Bockiii/deezloadermx-docker#18]
Can't figure out why it's not working on my raspberry pi. Still getting this ERR_CONNECTION_REFUSED error on my browser...

**Comment by Bockiii** [comment]
sounds like you haven't port forwarded the correct port? Whats your docker run or compose call?

**Comment by titouan-pellerin** [comment]
docker run -d --name Deezldr -v Musique -v config -e PUID=1000 -e PGID=1000 -p 1730:1730 bocki/deezloaderrmx

I tried this one, on a few other without some parameters. But same resultat every time. I'm a newbie to docker, so maybe I'm doing something wrong...

**Comment by titouan-pellerin** [comment]
Is it only working for pi4 ?

**Comment by tempestnano** [comment]
The arm32v7 version should work for all rpi's iirc.

**Comment by tempestnano** [comment]
Try to pull the logs
docker logs Deezldr
Are you sure you are putting the correct port in your browser?

**Comment by titouan-pellerin** [comment]
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 267.
[cont-init.d] 10-adduser: executing...
[cont-init.d] 10-adduser: exited 267.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 267.
[cont-init.d] 99-custom-files: executing...
[cont-init.d] 99-custom-files: exited 267.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
Here are the logs
And yes I suppose that i'm putting the correct port : http://192.168.0.39:1730 
192.168.0.39 being my raspberry ip address.

And to run I did this : 
docker run -d --name Deezldr -v Musique -v config -e PUID=1000 -e PGID=1000 -p 1730:1730 bocki/deezloaderrmx

**Comment by tempestnano** [comment]
Which rpi are you using?  I believe running this on a zero would cause this. It shouldn't be hard to add an arm32v6 dockerfile if that is the case.

**Comment by titouan-pellerin** [comment]
It's an old one, Rpi1 B+, my pi4 is currently running a plex server...

**Comment by tempestnano** [comment]
I spoke too soon, It appears that the alpine base that is used here does not have an arm32v6 build.

**Comment by titouan-pellerin** [comment]
Oh, and in your opinion is there any possible solution ?

**Comment by tempestnano** [comment]
We would need to add arm32v6 to [linuxserver/docker-baseimage-alpine](https://github.com/linuxserver/docker-baseimage-alpine), and build it all in one go.  It is doable, but would likely be time consuming.

**Comment by Bockiii** [comment]
I agree, too much work for the use case.

Additionally, the devs discontinued deezloader remix today. See their repo and my description. There will not be any more updates to deezloader, so if something breaks, its broken.

There is a successor in development, check that one out. There is no armv6 version available for that rn too.
