### ISSUE TITLE
Some songs are not fully downloading

### ISSUE THREAD

**Issue by dlchamp** [Bockiii/deezloadermx-docker#19]
Like many people, when they first started using this tool, they downloaded a bunch of music.   For some reason, I'm finding that some of those files that were downloaded are not complete.  
  
For instance, Foo Fighters/Greatest Hits/02 - Best of You.mp3.   In Plex, it stopped as 3:15 even though it's analyzed and shows audio to the end of the track.   I opened that same file in VLC on my desktop machine, stopped in the same spot.   Re-downloading usually fixes this, but is there any insight as to why songs aren't being downloaded to completion in the first place?   I've come across others, but assumed it was a Plex/Plexamp issue and didn't take notes on which other songs it's happened on.

**Comment by Bockiii** [comment]
I have seen that bug on reddit but have no experience with it myself.

But: Deezloader Rmx development has been stopped, please take a look at the successor Deemix. I also have a deemix docker container, so better switch to that.

https://hub.docker.com/r/bocki/deemix
