### ISSUE TITLE
Expose GUID / PID options in docker

### ISSUE THREAD

**Issue by ArbiterGR** [Bockiii/deezloadermx-docker#2]
Hi, could you give us the option to define user:group & umask inside docker using enviroment variables? Linux-server.io containers for example use -e GUID & -e PUID to define that. Reason is, i'm using unraid which writes everything with 777 nobody:users (99:100) as permissions on files and directories.  There's a script someone made and posted in unraid forums, that can easily implement this in your container https://forums.unraid.net/topic/39289-adapting-container-user-and-group-ids-to-the-host/

**Comment by Bockiii** [comment]
Hey,

I will look into this and add it soon.

**Comment by abnersnell** [comment]
This would be helpful for me also instead of everything created as user and group root on the host.  Thank you!

**Comment by Terror-Gene** [comment]
need this. i constantly cant move folders & stuff from deezloader. driving me bonkers :p

**Comment by santiagocvrt** [comment]
> need this. i constantly cant move folders & stuff from deezloader. driving me bonkers :p

Same thing here! +1 for this enhacement

**Comment by Bockiii** [comment]
Alright.. this took quite a bit longer than I'm comfortable sharing ;)

I think I've got it. Please test a new tag called "puidtest" in the docker hub.

This is an example:

```
docker run -d --name Deezldrtest \
              -v /path/to/my/music/:/downloads \
              -v /mydeezloaderconfig:/config \
              -e PUID=1337 \
              -e PGID=1338 \
              -p 1730:1730 \
              bocki/deezloaderrmx:puidtest
```

Please report back if it works for you. Thanks!

**Comment by ArbiterGR** [comment]
> Alright.. this took quite a bit longer than I'm comfortable sharing ;)
> 
> I think I've got it. Please test a new tag called "puidtest" in the docker hub.
> 
> This is an example:
> 
> ```
> docker run -d --name Deezldrtest \
>               -v /path/to/my/music/:/downloads \
>               -v /mydeezloaderconfig:/config \
>               -e PUID=1337 \
>               -e PGID=1338 \
>               -p 1730:1730 \
>               bocki/deezloaderrmx:puidtest
> ```
> 
> Please report back if it works for you. Thanks!

Thanks for taking the time to implement this!  I just tried it but it doesn't seem to do anything ?

These are my docker settings

![image](https://user-images.githubusercontent.com/3236764/65371717-2dd62400-dc6f-11e9-9300-e51818800486.png)

**Comment by Bockiii** [comment]
Well, you wanted it, you got it: I completely rebased the whole docker.
I switched from the node-alpine base to the lsio alpine base and changed the dockerfile/startscript dynamic. That means I had to do the node/npm stuff myself, but it means that I can piggyback off of the lsio user management...

.. which took another half-day to understand.

So: try the puidtest tag again.

Important! Since the lsio image has it's own use for a /config folder, I had to switch to /deezconfig.

Use this to start and report back if it worked:

```
docker run -d --name Deezldrtest \
              -v /path/to/my/music/:/downloads \
              -v /mydeezloaderconfig:/deezconfig \
              -e PUID=1337 \
              -e PGID=1338 \
              -p 1730:1730 \
              bocki/deezloaderrmx:puidtest
```

**Comment by ArbiterGR** [comment]
> Well, you wanted it, you got it: I completely rebased the whole docker.
> I switched from the node-alpine base to the lsio alpine base and changed the dockerfile/startscript dynamic. That means I had to do the node/npm stuff myself, but it means that I can piggyback off of the lsio user management...
> 
> .. which took another half-day to understand.
> 
> So: try the puidtest tag again.
> 
> Important! Since the lsio image has it's own use for a /config folder, I had to switch to /deezconfig.
> 
> Use this to start and report back if it worked:
> 
> ```
> docker run -d --name Deezldrtest \
>               -v /path/to/my/music/:/downloads \
>               -v /mydeezloaderconfig:/deezconfig \
>               -e PUID=1337 \
>               -e PGID=1338 \
>               -p 1730:1730 \
>               bocki/deezloaderrmx:puidtest
> ```

Totally my bad. It did work. Not changing /config to /deezconfig was my issue. Got it up and running now! 

Dude, thank you so much for all the work you've put into this container!

**Comment by Bockiii** [comment]
No, it really didnt work before :) the deezconfig thing came with the last version, after I rebased.

So it's working with the changed PUID and GUID in unraid? Folders are created in the correct user etc?

**Comment by ArbiterGR** [comment]
> No, it really didnt work before :) the deezconfig thing came with the last version, after I rebased.
> 
> So it's working with the changed PUID and GUID in unraid? Folders are created in the correct user etc?

Yes! PUID/GUID sets correctly to what i passed along on docker creation. Thanks again!

**Comment by Bockiii** [comment]
Awesome. I even managed to get around the new config folder, so I will update the "latest" tag with the new image. You will NOT have to use /deezconfig!! You can just use the previous /config folder.

Also, for running the container from here on, you should switch back to the "latest" tag.

issue closed :)
