### ISSUE TITLE
Successor

### ISSUE THREAD

**Issue by Uatschitchun** [Bockiii/deezloadermx-docker#21]
Is the new version down?

**Comment by MartinH0** [comment]
Yes seems like. @Bockiii would you be so kind and reuplaod it or host it somewhere else so people can install it again?
Ty!

**Comment by Bockiii** [comment]
Hi,

sorry,the link was old. Deemix was removed from dockerhub so I moved it to gitlab.

https://gitlab.com/Bockiii/deemix-docker

**Comment by Uatschitchun** [comment]
Thx, found it already.
