### ISSUE TITLE
Would you be willing to host an Raspberry Pi version?

### ISSUE THREAD

**Issue by brianinmaine** [Bockiii/deezloadermx-docker#3]
Thanks so much for this - it's amazing.
here's a modified version of your Dockerfile that works fine on my Pi:
```
FROM node:11-stretch-slim
ADD start-dzldr.sh /
RUN apt-get update && apt-get install -y  \
    bash \
    ca-certificates \
    wget \
    git \
    unzip \
    jq && \
    rm -rf /var/lib/apt/lists/* && \
    chmod 777 /start-dzldr.sh && \
    ln -sf /root/.config/Deezloader\ Remix/ /config && \
    ln -sf /downloads /root/Deezloader\ Music
EXPOSE 1730
ENTRYPOINT ["./start-dzldr.sh"]

```

**Comment by Bockiii** [comment]
I have no good testing opportunity for this as well. If you find a way, I will gladly add it as a tag. Until then...

**Comment by tempestnano** [comment]
This repo now works for arm32v7 (rpi), amd64, and arm64v8 (rpi4 when they switch to a 64-bit kernel) processors. Just pull bocki/deezloaderrmx:latest

**Comment by bluenote73** [comment]
Thank you!!
