### ISSUE TITLE
Save user token across device

### ISSUE THREAD

**Issue by Wdavery** [Bockiii/deezloadermx-docker#4]
Is it possible to define the user token as a docker env variable? That way the session can be automatically logged in across devices.

Currently it prompts for a login token on every new device, which makes it more difficult to use.

**Comment by auanasgheps** [comment]
It would be a great addition!

**Comment by Petahh** [comment]
+1

**Comment by Bockiii** [comment]
Even though that sounds interesting, I wouldn't even know where to start. This would mean accessing the login process on the website that electron builds, parsing the information and basically automate the login with bash scripting.

Not saying it's impossible, there are just a bunch of skills involved that I don't possess :)

Also, the token invalidates every 3 months, so you would have to update your compose files ever so often. Not sure if theres a benefit.

I will close this for now, if you find an awesome way how to do that, I can implement it.
