### ISSUE TITLE
[Enhancement] Is it possible to add reverse proxy capabilities? 

### ISSUE THREAD

**Issue by K6TPg6g9f** [Bockiii/deezloadermx-docker#7]
I have a lot of my stuff accessible through the internet behind reverse proxies, I tried to implement this as well, however components like socket.io seem to make this not a possibility. Is it possible to add this functionality?

**Comment by Bockiii** [comment]
I don't understand why it shouldn't be possible to use nginx to reverse proxy into the container. It's basically doing the same as every other container: Provide a port to the outside.

What happens if you try to do that? Do you get an error message of sorts?

**Comment by K6TPg6g9f** [comment]
I set up the webpage like any other container and the login page appears, the problem with this is socket.io. Deezloader is in a folder but socket.io doesnt seem to like living in a folder and as a result, I get 404 errors.

![socket io](https://user-images.githubusercontent.com/56618593/66970656-c0ef5780-f07d-11e9-8305-da2929df86ef.JPG)

![deezloader](https://user-images.githubusercontent.com/56618593/66970669-c8aefc00-f07d-11e9-8f40-2fdbfec85c7e.JPG)

nginx config (was trying to force this under deezloader)
![nginx](https://user-images.githubusercontent.com/56618593/66970729-f7c56d80-f07d-11e9-952c-c97abb74ecff.JPG)

**Comment by Bockiii** [comment]
I just tried this with the nginx-proxy-manager container (I'm not running nginx and configs myself, just use the container) and it works straight away. So it needs to be something in your config.

**Comment by K6TPg6g9f** [comment]
Is there a way to view your nginx config? Do you have deezloaderrmx is a folder? 
For example: example.com/deezloaderrmx/

**Comment by K6TPg6g9f** [comment]
I simplified my nginx config a lot and it still isnt working. When looking at deezloaderrmx without my proxy, socket.io loads under deezloader. For example, deezloaderrmx/socket.io. Since I have deezloader in a folder on my website, it doesnt load under deezloader/socker.io anymore, it tries to load without the folder.

example.com/deezloaderrmx/ does load the page but since deezloaderrmx is in a folder, socket.io tries to load like this example.com/socket.io. Which causes 404 errors and doesnt allow the ability to log into the interface.
Ideally it should load like normal. 
example.com/deezloaderrmx/socket.io

**Comment by K6TPg6g9f** [comment]
Yeah it's kinda odd, but the best way I can put it is that socket.io is relies on being part of deezloaderrmx as a component, just like js for example. But, when you put deezloaderrmx in a folder, socket.io doesnt "live" under deezloaderrmx anymore and it returns a 404 error

my screenshots from above shows this.

I looked into this and found this link which seems to describe my problem exactly and there is a solution, but I do not have the know how to apply it.

https://stackoverflow.com/questions/22919276/how-to-connect-socket-io-through-a-reverse-proxy

**Comment by Bockiii** [comment]
Yeah, I have no idea what you are really talking about :D

I don't know why you would need socket.io involved in this at all. If you want to run deezloader as part of a website, I don't think running it containerized is the best approach. If you just want to do reverse proxying, my assumption was always:
Outside like is example.com/deez
Nginx knows "ah, example.com/deez goes to my internal server 192.168.0.1 on port 8080" and forwards that information.

Since deezloader already provides a website and a port to listen to... I dont know what you are doing really.

Configure your nginx to point towards port 1730 of your deezloader container and that should be it...

**Comment by K6TPg6g9f** [comment]
> I don't think running it containerized is the best approach. If you just want to do reverse proxying, my assumption was always:
> Outside link is example.com/deez
> Everything going to example.com is going into Nginx
> Nginx knows "ah, example.com/deez goes to my internal server 192.168.0.1 on port 8080" and forwards that information.

This is correct, everything fowards, js, css, etc.. except for socket.io for some reason which causes the 404.

I do use other containers in the same way though like guacamole, sonarr, radarr, qbittorrent

So to explain my set up, I have a site that hosts all of these containers under one interface called organizr, everything works very well and is behind an nginx proxy server. I am able to continue on with my activities through the internet, I wanted to also have deezloaderrmx operate like the others, however this particular puzzle is hitting a snag.

I'll keep investigating I suppose, thanks guys for looking into it.

**Comment by K6TPg6g9f** [comment]
Found an even better link actually

https://stackoverflow.com/questions/25896225/how-do-i-get-socket-io-running-for-a-subdirectory

It looks like all I would have to do is edit app.js file in the container.

**Comment by Bockiii** [comment]
Ah okay... interesting :D 

Not really feasable for me to "fix" this in the container or to create a new tag for it, but if you test this and can describe which parts of the app.js you are actually changing, I could link to your answer on the front page, for other people having the same issue.

**Comment by Bockiii** [comment]
pinging @K6TPg6g9f  . If you want to describe it, go for it and I will link it, but I will close the issue for now.

**Comment by K6TPg6g9f** [comment]
Sorry I've been busy lately. I'm still working through a solution and I will comment back if I find one.

Thanks for closing the thread.

**Comment by tempestnano** [comment]
I don't know if this helps, but subdomain based reverse-proxy works fine. I gave up on subfolders.
My Nginx config (with letsencrypt ssl):
`server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name deez.*;
    include /config/nginx/ssl.conf;
    client_max_body_size 0;
    proxy_redirect off;
    proxy_buffering off;
    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_deez deezloader;
        proxy_pass http://$upstream_deez:1730;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }
}
`

**Comment by K6TPg6g9f** [comment]
Finally figured it out, just in case there are people who want to access deezloader from a subfolder this is what worked for me. There are a couple of things in the docker container itself you are going to have to edit.

Before you edit any files, back them up.

You can enter the container with this command `docker exec -it <containername> bash`. While in the container, copy the app.js file edit the app.js file with this command `vi /deezloaderremix/app/app.js`. In this file, there is a section called "server stuff". You would see this line `const io = require('socket.io').listen(server, {log: false, wsEngine: 'ws'})`. You need to add your subfolder here in the brackets. The following is an example. `const io = require('socket.io').listen(server, {log: false, wsEngine: 'ws', {path: '/deezloaderrmx/socket.io'})`

![14144441](https://user-images.githubusercontent.com/56618593/73715739-db247280-470c-11ea-9ed9-a71e22b0773c.JPG)

Next, you must edit the frontend file with this command `vi /deezloaderremix/app/public/js/frontend.js`. Near the top you would see the line `const socket = io.connect(window.location.href)`. You must edit it by adding the url and the subfolder deezloader would load from. The following is an example.
`const socket = io.connect('https://example.com', {path: "/deezloaderrmx/socket.io"})`

![32223323232](https://user-images.githubusercontent.com/56618593/73715862-3bb3af80-470d-11ea-93d3-fc558f03dbf6.JPG)

Finally, exit the container and restart the container with this command `docker restart deezloaderrmx`

Now when you load the page, the socket.io requests should be in the proper location.

![464564654](https://user-images.githubusercontent.com/56618593/73716072-ea57f000-470d-11ea-8c68-1850527e3241.JPG)

Nginx location block

![1969487](https://user-images.githubusercontent.com/56618593/73716145-1d9a7f00-470e-11ea-99f9-a542279b40d3.JPG)

I'm not sure if new updates reverts this or not so make backups. Thanks Bockiii for the great container!

**Comment by Bockiii** [comment]
interesting read, thanks for the information.

So yes, with the next update, those changes will revert. Here's what you could do tho:
- Create your own container, basing it off mine.
- Create a script that does the changes to the files (you can/should use environment variables so people can adapt it to their parameters)
- Enable the repository link on dockerhub to automatically build on upstream change. That way, you will get the updates from my container, plus the changes from your script.

You can test it and set it up if you want to and then post the link so I can help you with it.

**Comment by K6TPg6g9f** [comment]
Is it possible that the subfolder changes can be variable and instead of a script, it can be a container variable like grafana? Or a Base URL option like sonnar, radarr or jackett?

![61651651](https://user-images.githubusercontent.com/56618593/73804911-17171080-47bd-11ea-9edb-6f6ee755e593.JPG)

**Comment by Bockiii** [comment]
You can put it as an environment variable, but since the base code from deezloader does not support it, you will not get around patching their original file with the folder change.
You also can't prepare the file and just overwrite it as that will probably break whatever new version they roll out. So a script that performs text actions will probably be the best.

**Comment by K6TPg6g9f** [comment]
I could probably try to run a script, exactly how would I start? I dont have the skill set to create containers ect...

**Comment by K6TPg6g9f** [comment]
Giving a small update, I am now using the dev branch and the previous instructions seems to have to be adjusted. These is the only instructions I did to make it work again.

> Next, you must edit the frontend file with this command `vi /deezloaderremix/app/public/js/frontend.js`. Near the top you would see the line `const socket = io.connect(window.location.href)`. You must edit it by adding the url and the subfolder deezloader would load from. The following is an example.
> `const socket = io.connect('https://example.com', {path: "/deezloaderrmx/socket.io"})`
> 
> Finally, exit the container and restart the container with this command `docker restart deezloaderrmx`

I'm still working on to try to perhaps get a script started when I get time.
