### ISSUE TITLE
Password Protection?

### ISSUE THREAD

**Issue by zhdenny** [Bockiii/deezloadermx-docker#9]
I would like to put this on a remote server and access remotely. Are there any plans to implement any security/password or anything like that?

As it currently stands, if I expose this service to the open, anyone with the address can access and start messing around....

I'm specifically asking with respect to the new REST API functions. It's weird there isn't even an API key for this. I could try to throw the Web UI through an auth service like a simple nginx htpasswd type thing.....but then I would have to expose the /api addresses in order for the API to work. Since there is no API key, this makes it rather insecure.

**Comment by zhdenny** [comment]
Asked the Deezloader Remix dev about it....don't think there will ever be a place for Web UI Native Authentication or API key.

But instead, it looks like nginx htpasswd auth could still work.....and accessing the API would just be something like this in the HTTP POST
https://username:password@deezloader.domain.com/api/download

**Comment by Bockiii** [comment]
Hi, 

sorry, but this is not in scope for the container. I don't want to join the depths of making something actually safe from the outside. I'd rather give the definite "it's not safe to just open up to the outside" than to give a false sense of security by implementing something i found off of stackoverflow.

So no, won't be implementing this. If you want to open this up to the outside world, use reverse proxy authentications.
